<?php

namespace App\Database\Repositories\User;

use App\Database\Entities\User\User;
use Doctrine\ORM\EntityRepository;

/**
 * Class UserRepository
 * @package App\Database\Repositories\User
 */
class UserRepository extends EntityRepository implements UserRepositoryInterface
{
    /**
     * Find all Users
     * - Including Admin
     *
     * @return array
     */
    public function findAll(): array
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    /**
     * Find all Users (Non-Admin)
     * - Excluding Admin
     *
     * @return array
     */
    public function findAllUser(): array
    {
        return $this->findByRole(["User", "Guest"]);
    }

    /**
     * Find User By Id
     *
     * @param $id
     * @return object|null
     */
    public function findById($id)
    {
        return $this->findOneBy(['id' => $id]);
    }

    /**
     * Find Users By Role(s)
     *
     * @param string|array $roles
     * @return mixed
     */
    public function findByRole($roles)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select("users")
            ->from(User::class, 'users')
            ->join('users.roles', 'role')
            ->where('role.name IN (:pRoles)')
            ->setParameter('pRoles', $roles)
            ->getQuery()
            ->getResult()
        ;
    }
}
